version: '3'
services:
    mysql:
        image: mariadb:11.2.2-jammy
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root1234
            - MYSQL_DATABASE=famistrywp
            - MYSQL_USER=famistry
            - MYSQL_PASSWORD=fam1234
        restart: always
    wordpress:
        image: wordpress:6.4.2-php8.3-fpm-alpine
        volumes:
            - ./data/html:/var/www/html
        depends_on:
            - mysql
        environment:
            - WORDPRESS_DB_HOST=mysql
            - MYSQL_ROOT_PASSWORD=root1234
            - WORDPRESS_DB_NAME=famistrywp
            - WORDPRESS_DB_USER=famistry
            - WORDPRESS_DB_PASSWORD=fam1234
            - WORDPRESS_TABLE_PREFIX=wp_
        links:
            - mysql
        restart: always
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin:5.2.1-apache
        restart: always
        ports:
            - '9080:80'
        environment:
            - PMA_HOST=mysql
            - MYSQL_ROOT_PASSWORD=root1234
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./data/html:/var/www/html
        ports:
            - '5080:80'
        links:
            - wordpress
